project:
  type: website

website:
  title: "Mohammed Alshaghathirah"
  navbar:
    left:
      - text: About Me
        href: index.qmd
      - text: Projects
        href: projects/index.qmd

format:
  html:
    theme: cosmo
    toc: true
